#!/bin/bash
set -ex

[[ -e ~/.bashrc ]] && . ~/.bashrc
. /sources/build/.env

bash "${SCRIPTDIR}/scripts/4.4-setting-up-the-environment.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.4-binutils-pass-1.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.5-gcc-pass-1.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.6-linux-api-headers.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.7-glibc.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.8-libstdc.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.9-binutils-pass-2.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.10-gcc-pass-2.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.11-tcl.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.12-expect.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.13-dejagnu.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.14-m4.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.15-ncurses.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.16-bash.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.17-bison.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.18-bzip2.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.19-coreutils.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.20-diffutils.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.21-file.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.22-findutils.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.23-gawk.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.24-gettext.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.25-grep.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.26-gzip.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.27-make.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.28-patch.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.29-perl.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.30-sed.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.31-tar.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.32-texinfo.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.33-util-linux.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.34-xz.sh"
bash "${SCRIPTDIR}/scripts/toolchain/pacstuffs.sh"
bash "${SCRIPTDIR}/scripts/toolchain/5.35-strip.sh"
