#!/bin/bash
set -e

bash $SCRIPTDIR/chroot/6.35-libtool.sh
bash $SCRIPTDIR/chroot/6.36-gdbm.sh
bash $SCRIPTDIR/chroot/6.37-gperf.sh
bash $SCRIPTDIR/chroot/6.38-expat.sh
bash $SCRIPTDIR/chroot/6.39-inetutils.sh
bash $SCRIPTDIR/chroot/6.40-perl.sh
bash $SCRIPTDIR/chroot/6.41-xmlparser.sh
bash $SCRIPTDIR/chroot/6.42-intltool.sh
bash $SCRIPTDIR/chroot/6.43-autoconf.sh
bash $SCRIPTDIR/chroot/6.44-automake.sh
bash $SCRIPTDIR/chroot/6.45-xz.sh
bash $SCRIPTDIR/chroot/6.46-kmod.sh
bash $SCRIPTDIR/chroot/6.47-gettext.sh
bash $SCRIPTDIR/chroot/6.48-libelf.sh
bash $SCRIPTDIR/chroot/6.49-libffi.sh
bash $SCRIPTDIR/chroot/6.50-openssl.sh
bash $SCRIPTDIR/chroot/6.51-python.sh
bash $SCRIPTDIR/chroot/6.52-ninja.sh
bash $SCRIPTDIR/chroot/6.53-meson.sh
bash $SCRIPTDIR/chroot/6.54-procps-ng.sh
bash $SCRIPTDIR/chroot/6.55-e2fsprogs.sh
bash $SCRIPTDIR/chroot/6.56-coreutils.sh
bash $SCRIPTDIR/chroot/6.57-check.sh
bash $SCRIPTDIR/chroot/6.58-diffutils.sh
bash $SCRIPTDIR/chroot/6.59-gawk.sh
bash $SCRIPTDIR/chroot/6.60-findutils.sh
bash $SCRIPTDIR/chroot/6.61-groff.sh
bash $SCRIPTDIR/chroot/6.62-grub.sh
bash $SCRIPTDIR/chroot/6.63-less.sh
bash $SCRIPTDIR/chroot/6.64-gzip.sh
bash $SCRIPTDIR/chroot/6.65-iproute2.sh
bash $SCRIPTDIR/chroot/6.66-kbd.sh
bash $SCRIPTDIR/chroot/6.67-libpipeline.sh
bash $SCRIPTDIR/chroot/6.68-make.sh
bash $SCRIPTDIR/chroot/6.69-patch.sh
bash $SCRIPTDIR/chroot/6.70-sysklogd.sh
bash $SCRIPTDIR/chroot/6.71-sysvinit.sh
bash $SCRIPTDIR/chroot/6.72-eudev.sh
bash $SCRIPTDIR/chroot/6.73-util-linux.sh
bash $SCRIPTDIR/chroot/6.74-man-db.sh
bash $SCRIPTDIR/chroot/6.75-tar.sh
bash $SCRIPTDIR/chroot/6.76-texinfo.sh
bash $SCRIPTDIR/chroot/6.77-vim.sh
